Repository Uspacy/uspacy-store, pull requests merged in 2023-11, with the labels that each got.

#40 [1896] fix: fixing edit tasks in groups
  package.json
  src/store/groups/actions.ts
  src/store/groups/index.ts
  src/store/groups/types.ts
  src/store/tasks/index.ts
  yarn.lock
Labels: size/m

#41 [1971] go to new messages
  package.json
  src/helpers/messenger.ts
  src/store/messenger/messenger/index.ts
  src/store/messenger/messengerExternal/index.ts
  yarn.lock
Labels: size/l

#42 [1698] feature: updating certain date or period
  package.json
  src/store/tasks/index.ts
  yarn.lock
Labels: size/s

#43 [1617] Created Billings store
  package.json
  src/store/profile/actions.ts
  src/store/profile/index.ts
  src/store/profile/types.ts
  yarn.lock
Labels: size/l

#44 fix: fixing dependencies
  package.json
Labels: size/s

#46 [fix] improve logic go to unread messages
  package.json
  src/helpers/messenger.ts
  src/store/messenger/messenger/actions.ts
  src/store/messenger/messenger/index.ts
  src/store/messenger/messengerExternal/index.ts
Labels: size/l

#47 fix read all messages
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/s

#48 fix read all messages
  package.json
  src/helpers/messenger.ts
  src/store/messenger/messenger/index.ts
Labels: size/s

#45 [1628] Fixed loading deps
  package.json
  src/store/profile/index.ts
  src/store/profile/types.ts
Labels: size/m

#49 [1625] - feature. CRM relations in tasks
  package.json
  src/store/tasks/actions.ts
  yarn.lock
Labels: size/m

#51 [2124] go to message fix
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/xs

#52 [1617] Divide loading process
  package.json
  src/store/profile/index.ts
  src/store/profile/types.ts
  yarn.lock
Labels: size/m

#54 [2124] go to message fix
  package.json
Labels: size/xs

#55 [1960] features: new groups kanban
  package.json
  src/store/tasks/actions.ts
  src/store/tasks/index.ts
  src/store/tasks/types.ts
  src/store/tasksStages/actions.ts
  yarn.lock
Labels: size/m

#57 [2070] feature: update usapcy store version
  package.json
  yarn.lock
Labels: size/s
