Repository Uspacy/uspacy-store, pull requests merged in 2023-10, with the labels that each got.

#8 feature: adding mass editing
  package.json
  src/helpers/stringsHelper.ts
  src/store/tasks/actions.ts
  src/store/tasks/index.ts
  yarn.lock
Labels: size/m

#9 feature: adding tasks fields
  package.json
  src/store/tasks/actions.ts
  src/store/tasks/index.ts
  src/store/tasks/types.ts
  yarn.lock
Labels: size/m

#10 feature: Updating mass actions
  package.json
  src/store/tasks/actions.ts
  src/store/tasks/index.ts
  yarn.lock
Labels: size/m

#11 fix: up v
  package.json
Labels: size/xs

#12 feature: filtering application users
  package.json
  src/store/users/index.ts
  yarn.lock
Labels: size/s

#13 feature: updating entities
  package.json
  src/store/crmEntities/index.ts
Labels: size/xs

#14 [1702] fix: fixing clearing kanban stages
  package.json
  src/store/tasksStages/index.ts
Labels: size/xs

#15 [1690] feature: implement company
  package.json
  src/helpers/disabledPermissions.ts
  src/store/groups/actions.ts
  src/store/groups/index.ts
  src/store/groups/types.ts
  src/store/roles/actions.ts
  src/store/roles/disableDeleting.enum.ts
  src/store/roles/index.ts
  src/store/roles/role.enums.ts
  src/store/roles/types.ts
  yarn.lock
Labels: size/l, size/xl

#16 up sdk version
  package.json
  yarn.lock
Labels: size/s

#17 [1690] hotfix: groups types
  package.json
  src/store/groups/index.ts
  src/store/groups/types.ts
Labels: size/xs

#18 [1708]: add filling multiple users
  package.json
  src/store/tasks/index.ts
Labels: size/m

#19 [1690] feature: newsfeed implementation
  package.json
  src/store/comments/actions.ts
  src/store/comments/index.ts
  src/store/comments/types.ts
  src/store/index.ts
  src/store/newsfeed/actions.ts
  src/store/newsfeed/index.ts
  src/store/newsfeed/types.ts
  yarn.lock
Labels: size/xl

#20 up sdk version
  package.json
  yarn.lock
Labels: size/m

#22 Fix/up versions sdk
  package.json
Labels: size/xs

#23 [1841] fix: updating payments
  package.json
  yarn.lock
Labels: size/s

#25 [1690] bugfix: fix for posts
  package.json
  src/store/newsfeed/actions.ts
  yarn.lock
Labels: size/s, size/xs

#27 [1690] bugfix: create update methods
  package.json
  src/store/newsfeed/actions.ts
  yarn.lock
Labels: size/m

#28 [1690] bugfix: fix user methods
  package.json
  src/store/users/actions.ts
Labels: size/xs

#24 [1845] feature: implement migrations
  package.json
  src/store/index.ts
  src/store/migrations/amo/actions.ts
  src/store/migrations/amo/index.ts
  src/store/migrations/amo/types.ts
  src/store/migrations/bitrix24/actions.ts
  src/store/migrations/bitrix24/index.ts
  src/store/migrations/bitrix24/types.ts
  src/store/migrations/dataPresence/actions.ts
  src/store/migrations/dataPresence/index.ts
  src/store/migrations/dataPresence/types.ts
  src/store/migrations/index.ts
  src/store/migrations/progress/actions.ts
  src/store/migrations/progress/getAllSystemsStatus/actions.ts
  src/store/migrations/progress/getAllSystemsStatus/index.ts
  src/store/migrations/progress/index.ts
  src/store/migrations/stopImport/actions.ts
  src/store/migrations/stopImport/index.ts
  src/store/migrations/systemsWithKey/actions.ts
  src/store/migrations/systemsWithKey/index.ts
  src/store/migrations/systemsWithKey/types.ts
  yarn.lock
Labels: size/l

#1 Applications reducer
  package.json
  src/store/apps/actions.ts
  src/store/apps/index.ts
  src/store/apps/types.ts
  src/store/groups/index.ts
  src/store/groups/types.ts
  src/store/index.ts
  src/store/newsfeed/index.ts
  src/store/newsfeed/types.ts
  yarn.lock
Labels: size/l, size/m

#32 up v sdk
  package.json
  yarn.lock
Labels: size/s

#34 upd v
  package.json
  yarn.lock
Labels: size/s

#36 [1698] feature: update type for new fields
  package.json
  src/store/tasks/index.ts
  yarn.lock
Labels: size/m

#37 [1827] feature: add meta to webhook method
  package.json
  src/store/webhooks/actions.ts
  src/store/webhooks/index.ts
  yarn.lock
Labels: size/s

#35 [1906] move messenger and external messenger into general store
  package.json
  src/helpers/messenger.ts
  src/store/index.ts
  src/store/messenger/index.ts
  src/store/messenger/messenger/actions.ts
  src/store/messenger/messenger/index.ts
  src/store/messenger/messenger/types.ts
  src/store/messenger/messengerExternal/actions.ts
  src/store/messenger/messengerExternal/index.ts
  src/store/messenger/messengerExternal/types.ts
  yarn.lock
Labels: size/xl, size/XXL

#39 upd version
  package.json
Labels: size/xs
