Repository Uspacy/uspacy-store, pull requests merged in 2023-12, with the labels that each got.

#59 [2169] bugfix: fix bugs for groups
  package.json
  src/store/groups/actions.ts
  src/store/groups/index.ts
  src/store/groups/types.ts
Labels: size/s

#60 [2169] bugfix: invite users to group
  package.json
  src/store/groups/index.ts
  src/store/groups/types.ts
Labels: size/s

#61 [1617] up v
  package.json
  yarn.lock
Labels: size/s

#62 [1617] add redusers requisite
  package.json
  src/helpers/checkBasicRequisite.ts
  src/store/profile/index.ts
Labels: size/s, size/xs

#64 [2185] unread counter fix
  package.json
  src/helpers/messenger.ts
  src/store/messenger/messenger/index.ts
  src/store/messenger/messengerExternal/index.ts
Labels: size/s, size/xs

#65 [1789] up v for sdk
  package.json
  yarn.lock
Labels: size/s

#66 [2040] - feature. leads funnel
  package.json
  src/store/index.ts
  src/store/leadsFunnel/actions.ts
  src/store/leadsFunnel/index.ts
  src/store/leadsFunnel/types.ts
  yarn.lock
Labels: size/m

#67 [1789] you are dragged
  package.json
  src/helpers/messenger.ts
  src/store/messenger/messenger/index.ts
Labels: size/m

#68 [2070] feature: update email params for letters
  package.json
  src/store/email/actions.ts
  src/store/email/types.ts
  yarn.lock
Labels: size/s

#69 [2070] feature: update email filters
  package.json
  src/store/email/index.ts
  yarn.lock
Labels: size/s
