Repository Uspacy/uspacy-store, pull requests merged in 2024-12, with the labels that each got.

#161 [4162] feat: analytics constructor
  package.json
  src/store/analytics/actions.ts
  src/store/analytics/index.ts
  src/store/analytics/types.ts
  src/store/index.ts
  yarn.lock
Labels: size/l

#158 [4487] feat: incoming webhooks
  package.json
  src/store/webhooks/actions.ts
  src/store/webhooks/index.ts
  src/store/webhooks/types.ts
Labels: size/l

#163 [4290] feature: new comments development/store
  package.json
  src/helpers/notifications.ts
  src/store/comments/actions.ts
  src/store/comments/index.ts
  src/store/comments/types.ts
  src/store/index.ts
  yarn.lock
Labels: size/l

#165 [4537] fix: add filter fields
  package.json
  src/store/crm/filters/index.ts
  src/store/crm/filters/types.ts
Labels: size/s

#164 [4554] fix: permission universal entities
  package.json
  src/store/crm/items/index.ts
Labels: size/xs

#167 [4162] feat: change meta analytics
  package.json
  src/store/analytics/actions.ts
  src/store/analytics/index.ts
  yarn.lock
Labels: size/l, size/s

#169 [4633] fix: stage move
  package.json
  src/store/crm/items/index.ts
Labels: size/xs

#168 [4434] feat: change structure
  package.json
  src/store/announcers/index.ts
  yarn.lock
Labels: size/l, size/s

#170 [4633] fix: check stages for move kanban
  package.json
  src/store/crm/items/index.ts
Labels: size/l

#171 [4540] feature: email signatures development
  package.json
  src/store/email/actions.ts
  src/store/email/index.ts
  src/store/email/types.ts
  yarn.lock
Labels: size/l

#172 [4434] feat: data with attributes
  package.json
  src/store/announcers/index.ts
  yarn.lock
Labels: size/s

#166 [4611] bugfix: crm tasks link
  package.json
  src/helpers/notifications.ts
Labels: size/xs

#174 [4540] feature: signatures tarrifs restrictions
  package.json
  src/store/email/actions.ts
  yarn.lock
Labels: size/l, size/s

#173 [4434] feat: change structure
  package.json
  src/store/announcers/index.ts
  yarn.lock
Labels: size/s
