Repository Uspacy/uspacy-store, pull requests merged in 2024-07, with the labels that each got.

#124 [2660] feature: email card crm
  package.json
  src/store/drawersManagement/index.ts
  src/store/drawersManagement/types.ts
  src/store/email/index.ts
  src/store/email/types.ts
Labels: size/m, size/s

#108 [2991] settings integration
  package.json
  src/store/crmTasks/index.ts
  src/store/drawersManagement/index.ts
  src/store/drawersManagement/types.ts
  src/store/email/actions.ts
  src/store/email/index.ts
  src/store/email/types.ts
  yarn.lock
Labels: size/l, size/m

#126 [2660] feature: add crm entities for drawer management
  package.json
  src/store/drawersManagement/index.ts
  src/store/drawersManagement/types.ts
Labels: size/xs

#129 [3358] feature: add vertical sorting for tasks table store
  package.json
  src/store/tasks/index.ts
  yarn.lock
Labels: size/s

#98 [2186] feat: add automations store
  package.json
  src/store/automations/actions.ts
  src/store/automations/index.ts
  src/store/automations/types.ts
  src/store/index.ts
  yarn.lock
Labels: size/l

#131 [2040] feat: up sdk
  package.json
  yarn.lock
Labels: size/s

#127 [3413] fix: fixed readbyAll
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/s, size/xs

#133 [2040] up v
  package.json
Labels: size/xs

#130 [3283] fix: fixed removed message
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/m

#134 [2040] feat: toggle switch active automations
  package.json
  src/store/automations/index.ts
Labels: size/xs

#128 [3498] bugfix: fix notifications title for smart obj
  package.json
  src/const.ts
  src/helpers/notifications.ts
Labels: size/m, size/s
