Repository Uspacy/uspacy-store, pull requests merged in 2024-11, with the labels that each got.

#153 [4006] fix: sort values in entity fields
  package.json
  src/store/crm/fields/index.ts
Labels: size/s

#152 [4358] feat: banner exists flag
  package.json
  src/store/announcers/actions.ts
  src/store/announcers/index.ts
  src/store/announcers/types.ts
  src/store/index.ts
  yarn.lock
Labels: size/l, size/m, size/s, size/xs

#154 [4358] feat: up v
  package.json
Labels: size/xs

#155 [4358] feat: crm tasks
  package.json
  src/store/crmTasks/actions.ts
  src/store/crmTasks/index.ts
Labels: size/l

#159 [4540] feature: email access by users and signature/store
  package.json
  yarn.lock
Labels: size/l, size/s

#144 [4067] feat: add merge method for roles
  package.json
  src/store/roles/index.ts
Labels: size/s

#162 fix: fixing selector for couchdb
  package.json
  yarn.lock
Labels: size/s
