Repository Uspacy/uspacy-store, pull requests merged in 2024-04, with the labels that each got.

#106 [2937] feature: kanban vertical sorting store
  package.json
  src/store/tasksStages/actions.ts
  src/store/tasksStages/types.ts
  yarn.lock
Labels: size/s

#99 [2746] set isInvite status
  package.json
  src/store/drawersManagement/index.ts
  src/store/drawersManagement/types.ts
  src/store/index.ts
  src/store/messenger/messengerExternal/index.ts
  yarn.lock
Labels: size/m, size/s

#105 [2825] fixed unread count
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/xs

#107 hotfix fetch document templates fields fix params
  package.json
  src/store/crmDocumentTemplates/actions.ts
Labels: size/xs

#109 [3051] disability to set page size
  package.json
  src/store/crmTasks/index.ts
Labels: size/xs

#110 [3079] bugfix: fix mentioned update
  package.json
  src/helpers/notifications.ts
Labels: size/xs

#103 [2782] up sdk
  package.json
  src/const.ts
  src/helpers/filterFieldsArrs.ts
  src/store/crmCompanies/index.ts
  src/store/crmContacts/index.ts
  src/store/crmDeals/index.ts
  src/store/crmEntities/index.ts
  src/store/crmLeads/index.ts
  src/store/crmProducts/index.ts
  src/store/crmTasks/index.ts
  yarn.lock
Labels: size/m, size/s

#111 [fix] change remove .table from notification helpers
  src/helpers/notifications.ts
Labels: size/xs
