Repository Uspacy/uspacy-store, pull requests merged in 2024-06, with the labels that each got.

#119 [3007] feat: change groups methods
  package.json
  src/store/groups/actions.ts
  src/store/groups/index.ts
  yarn.lock
Labels: size/m

#122 [3329] feat: change link for crm activity
  src/helpers/notifications.ts
Labels: size/xs

#121 [3329] feat: change activity for new routes
  package.json
  src/helpers/notifications.ts
  src/store/crmTasks/index.ts
  yarn.lock
Labels: size/m

#123 [3329] fix: editCompanyFromCard change
  package.json
  src/store/crmTasks/index.ts
Labels: size/s

#125 [3432] feature: OAuth microsoft integration store
  package.json
  src/store/email/actions.ts
  src/store/email/index.ts
  src/store/email/types.ts
  yarn.lock
Labels: size/m
