Repository Uspacy/uspacy-store, pull requests merged in 2024-03, with the labels that each got.

#95 original timestamp update
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/xs

#93 [2423] feature: add replicate method to tasks
  package.json
  src/store/tasks/actions.ts
  src/store/tasks/index.ts
  src/store/tasks/types.ts
  yarn.lock
Labels: size/m

#94 [2664] feature: add group modal state
  package.json
  src/store/groups/index.ts
  src/store/groups/types.ts
Labels: size/xs

#96 [2663] feature: handle user request to join group
  package.json
  src/store/groups/index.ts
  src/store/groups/types.ts
Labels: size/s

#84 [2070] feature: update email reducers
  package.json
  src/store/email/actions.ts
  src/store/email/index.ts
  src/store/email/types.ts
  yarn.lock
Labels: size/l

#104 [2968] up v
  package.json
  yarn.lock
Labels: size/s
