Repository Uspacy/uspacy-store, pull requests merged in 2024-08, with the labels that each got.

#136 [3366] fix: notifications links for crm fix
  package.json
  src/helpers/notifications.ts
  src/store/notifications/types.ts
  yarn.lock
Labels: size/s, size/xs

#137 [2448] feat: required only title for product
  package.json
  src/store/crmProducts/index.ts
Labels: size/xs

#139 [2448] Fix: crm kanban create universal entity card
  package.json
  src/store/crmEntities/index.ts
Labels: size/s, size/xs

#135 [3393] feat: activity filters
  package.json
  src/const.ts
  src/helpers/filterFieldsArrs.ts
  src/store/crmTasks/actions.ts
  src/store/crmTasks/index.ts
  src/store/crmTasks/types.ts
  yarn.lock
Labels: size/l, size/XXL
