Repository Uspacy/uspacy-store, pull requests merged in 2024-02, with the labels that each got.

#77 [2520] feature: fixes for groups
  package.json
  src/store/groups/index.ts
  yarn.lock
Labels: size/m

#79 [2520] feature: up v
  package.json
  yarn.lock
Labels: size/s

#78 [2355] feature: new major update for templates
  package.json
  src/store/tasks/actions.ts
  src/store/tasks/index.ts
  src/store/tasks/types.ts
  yarn.lock
Labels: size/xl

#70 [1734] widget create integration
  package.json
  src/store/messenger/messenger/actions.ts
  src/store/messenger/messenger/index.ts
  src/store/messenger/messenger/types.ts
  yarn.lock
Labels: size/l, size/m

#82 up v
  package.json
Labels: size/xs

#85 [2585] fix: fix default boolean operator
  package.json
  src/store/tasks/index.ts
Labels: size/xs

#75 [2371] feature: upd for notifications
  package.json
  src/helpers/notifications.ts
  src/store/notifications/types.ts
Labels: size/s

#86 [2371] feature: fix link for notifications
  package.json
  src/helpers/notifications.ts
  src/store/notifications/types.ts
  yarn.lock
Labels: size/m, size/s, size/xs

#87 [2371] hotfix: fix link for posts
  package.json
  src/helpers/notifications.ts
Labels: size/s

#88 [2371] hotfix: fix mentioned
  package.json
  src/helpers/notifications.ts
  src/store/notifications/actions.ts
Labels: size/s

#89 [2371] hotfix: fix link for notes
  package.json
  src/helpers/notifications.ts
Labels: size/xs

#90 up v
  package.json
Labels: size/xs

#91 [2371] hotfix: fix for old notes
  package.json
  src/helpers/notifications.ts
Labels: size/s

#92 [2462] feature: remove unallocated column
  package.json
  src/store/tasks/index.ts
Labels: size/xs

#80 [2494] drafts develop
  package.json
  src/helpers/messenger.ts
  src/store/messenger/messenger/index.ts
  src/store/messenger/messengerExternal/index.ts
  yarn.lock
Labels: size/m, size/s
