Repository Uspacy/uspacy-store, pull requests merged in 2024-05, with the labels that each got.

#115 [2045] feature: delegation of tasks store
  package.json
  src/store/crmCompanies/index.ts
  src/store/crmDocumentTemplates/actions.ts
  src/store/tasks/actions.ts
  src/store/tasks/index.ts
  yarn.lock
Labels: size/m

#117 [3198] feature: update loaders for profile service
  package.json
  src/store/users/index.ts
  src/store/users/types.ts
Labels: size/l

#118 [1751] fb and insta integration
  package.json
  src/store/messenger/messenger/index.ts
  yarn.lock
Labels: size/s

#112 [3080] last message and coun fix
  package.json
  src/const.ts
  src/store/messenger/messenger/index.ts
Labels: size/m

#113 [3081] counter fix
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/m, size/xs
