Repository Uspacy/uspacy-store, pull requests merged in 2025-04, with the labels that each got.

#180 [3229] feat: add forms reducer
  package.json
  src/helpers/forms.ts
  src/store/forms/actions.ts
  src/store/forms/index.tsx
  src/store/forms/types.ts
  src/store/index.ts
  yarn.lock
Labels: size/l, size/m, size/XXL

#206 [no-task] fix: build fix
  package.json
  src/hooks/redux.ts
  yarn.lock
Labels: size/m

#207 [fix] added first automation
  package.json
  src/store/automations/index.ts
Labels: size/xs

#209 [sentry][USPACY-1V1] add aborted for template document fields
  package.json
  src/store/crmDocumentTemplates/index.ts
  yarn.lock
Labels: size/m

#210 up package
  package.json
  yarn.lock
Labels: size/m, size/xs

#211 [no-task] add resolutions
  package.json
  yarn.lock
Labels: size/s

#208 [5314] fix: fix read messages for ext lines
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/xs

#214 [5314] fix: read ext chat fix
  package.json
  src/store/messenger/messenger/index.ts
  src/store/messenger/messengerExternal/index.ts
Labels: size/m

#217 [5217] fix: read in two tabs fix
  package.json
  src/helpers/messenger.ts
Labels: size/xs

#218 [5276] feat: dashboard
  package.json
  src/helpers/dashboardHelper.ts
  src/store/analytics/actions.ts
  src/store/analytics/index.ts
  src/store/analytics/types.ts
  yarn.lock
Labels: size/l

#219 [5576] fix: chat members fix
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/xs

#220 [3396] feature: amount deals and smart objects
  package.json
  src/store/crm/items/actions.ts
  src/store/crm/items/index.ts
  src/store/crm/items/types.ts
  yarn.lock
Labels: size/m

#221 [5281] feat: users filter
  package.json
  src/const.ts
  src/store/profile/index.ts
  src/store/users/actions.ts
  src/store/users/index.ts
  src/store/users/types.ts
  yarn.lock
Labels: size/l
