Repository Uspacy/uspacy-store, pull requests merged in 2025-02, with the labels that each got.

#188 Revert 4544 revert logic
  package.json
  src/store/roles/index.ts
Labels: size/l

#189 4544 permission logic
  package.json
  src/store/roles/index.ts
Labels: size/l

#194 [4975] feature: new tasks kanban
  package.json
  src/store/tasks/actions.ts
  src/store/tasks/index.ts
  src/store/tasks/types.ts
  yarn.lock
Labels: size/l, size/m

#192 [5098] fix: fixed open unread chat
  package.json
  src/store/messenger/messenger/index.ts
Labels: size/s, size/xs

#195 [5188]feat: analytic report up store
  package.json
  yarn.lock
Labels: size/l

#196 [5189] fix: add check no tasks for deals items
  package.json
  src/helpers/filterFieldsArrs.ts
  src/store/crm/items/actions.ts
Labels: size/m, size/s

#197 [4969] feat call roles
  package.json
  src/helpers/disabledPermissions.ts
  src/store/roles/index.ts
  src/store/roles/role.enums.ts
Labels: size/m

#193 [5062] feature: zoom gmeeting integrations
  package.json
  src/store/auth/actions.ts
  src/store/auth/index.ts
  src/store/auth/types.ts
  src/store/calendars/actions.ts
  src/store/calendars/index.ts
  src/store/calendars/types.ts
  src/store/crmTasks/actions.ts
  src/store/crmTasks/index.ts
  src/store/crmTasks/types.ts
  src/store/index.ts
  yarn.lock
Labels: size/xl
