Repository Uspacy/uspacy-store, pull requests merged in 2025-01, with the labels that each got.

#175 [fix] moveItemFromStageToStage total count add optional chaining
  package.json
  src/store/crm/items/index.ts
Labels: size/xs

#177 [4766] feat: multi drawer crm
  package.json
  src/store/crm/items/index.ts
Labels: size/xs

#176 [4742] feature: new billing
  package.json
  src/const.ts
  src/store/auth/actions.ts
  src/store/auth/index.ts
  src/store/auth/types.ts
  yarn.lock
Labels: size/l

#181 [feat] user settings update interface
  package.json
  yarn.lock
Labels: size/s

#184 [4754] feat: up sdk
  package.json
  yarn.lock
Labels: size/l, size/s

#186 [4789] feat: funnel permissions
  package.json
  yarn.lock
Labels: size/l, size/s

#160 [4544] feat: permissions funnels
  package.json
  src/store/roles/actions.ts
  src/store/roles/index.ts
  src/store/roles/types.ts
  yarn.lock
Labels: size/l

#185 [4811] fix: add check entityCode
  package.json
  src/store/crm/items/index.ts
Labels: size/xs

#187 [2795] history crm
  package.json
  src/store/history/index.ts
Labels: size/xs
