Repository Uspacy/uspacy-store, pull requests merged in 2025-03, with the labels that each got.

#198 [5223] Feat: installed apps
  package.json
  yarn.lock
Labels: size/l, size/s

#201 up sdk and store v
  package.json
  yarn.lock
Labels: size/s

#200 [5234] feature: turn on activities in task kanban card
  package.json
  yarn.lock
Labels: size/l, size/s

#202 [3396] feature: new crm kanban
  package.json
  src/store/crm/items/types.ts
Labels: size/xs

#205 [5064] feat: permission department
  package.json
  src/helpers/disabledPermissions.ts
  src/store/departments/actions.ts
  src/store/roles/index.ts
  src/store/users/index.ts
  yarn.lock
Labels: size/l, size/m

#204 [4712] feat: profile custom fields
  package.json
  src/const.ts
  src/store/crm/fields/actions.ts
  src/store/crmEntities/actions.ts
  src/store/crmTasks/index.ts
  src/store/profile/actions.ts
  src/store/profile/index.ts
  src/store/profile/types.ts
  src/store/users/actions.ts
  yarn.lock
Labels: size/l

#203 [5390] feat: undistributed update
  package.json
  src/helpers/messenger.ts
  src/store/roles/index.ts
  yarn.lock
Labels: size/l, size/s

#191 [4635] crm connections for ext lines
  package.json
  src/store/messenger/messengerExternal/index.ts
  src/store/messenger/messengerExternal/types.ts
Labels: size/m
