Repository Uspacy/uspacy-store, pull requests merged in 2025-07, with the labels that each got.

#226 [5376] feature: email templates
  package.json
  src/store/index.ts
  src/store/marketing/actions.ts
  src/store/marketing/index.ts
  src/store/marketing/types.ts
  yarn.lock
Labels: size/l

#236 [2891] feat: trash
  package.json
  src/helpers/getTrashFilterByEntity.ts
  src/helpers/normalizeTrash.ts
  src/store/index.ts
  src/store/trash/actions.ts
  src/store/trash/index.ts
  src/store/trash/types.ts
  yarn.lock
Labels: size/l

#239 [2891] feat: up sdk
  package.json
  yarn.lock
Labels: size/s

#230 [5735] feat: forms settings design tab
  package.json
  src/store/forms/index.tsx
  yarn.lock
Labels: size/l, size/m
