Repository Uspacy/uspacy-store, pull requests merged in 2025-05, with the labels that each got.

#215 [5569] feature: stripe integration
  package.json
  src/store/auth/actions.ts
  src/store/auth/index.ts
  src/store/auth/types.ts
  src/store/payments/index.ts
  src/store/payments/types.ts
  yarn.lock
Labels: size/xl

#178 [4742] feature: add new coupons
  package.json
  src/store/auth/actions.ts
  src/store/auth/index.ts
  src/store/auth/types.ts
  yarn.lock
Labels: size/l, size/m

#222 [feat] bump axios to 1.9.0
  package.json
  yarn.lock
Labels: size/s

#216 [5137] feature: transfer of cases
  package.json
  src/store/index.ts
  src/store/transferOfCases/actions.ts
  src/store/transferOfCases/index.ts
  src/store/transferOfCases/types.ts
  yarn.lock
Labels: size/l

#223 [5742] feat: dnd for forms settings
  package.json
  src/helpers/forms.ts
  src/store/forms/index.tsx
  yarn.lock
Labels: size/m
